INSERT INTO franq VALUES(1,'Atlanta Hawks','Atlanta',1,'Central');
INSERT INTO franq VALUES(2,'Boston Celtics','Boston',2,'Atlantico');
INSERT INTO franq VALUES(3,'Chicago Bulls','Chicago',3,'Central');
INSERT INTO franq VALUES(4,'Cleveland Cavaliers','Cleveland',4,'Central');
INSERT INTO franq VALUES(5,'Dallas Mavericks','Dallas',5,'Medio-Oeste');
INSERT INTO franq VALUES(6,'Denver Nuggets','Denver',6,'Medio-Oeste');
INSERT INTO franq VALUES(7,'Detroit Pistons','Auburn Hills',7,'Central');
INSERT INTO franq VALUES(8,'Golden State Warriors','Oakland',8,'Pacifico');
INSERT INTO franq VALUES(9,'Houston Rockets','Houston',9,'Medio-Oeste');
INSERT INTO franq VALUES(10,'Indiana Pacers','Indianapolis',10,'Central');
INSERT INTO franq VALUES(11,'Los Angeles Clippers','Los Angeles',11,'Pacifico');
INSERT INTO franq VALUES(12,'Los Angeles Lakers','Los Angeles',11,'Pacifico');
INSERT INTO franq VALUES(13,'Memphis Grizzlies','Memphis',12,'Medio-Oeste');
INSERT INTO franq VALUES(14,'Miami Heat','Miami',13,'Atlantico');
INSERT INTO franq VALUES(15,'Milwaukee Bucks','Milwaukee',14,'Central');
INSERT INTO franq VALUES(16,'Minnesota Timberwolves','Minneapolis',15,'Medio-Oeste');
INSERT INTO franq VALUES(17,'New Jersey Nets','East Rutherford',16,'Atlantico');
INSERT INTO franq VALUES(18,'New Orleans Hornets','New Orleans',17,'Central');
INSERT INTO franq VALUES(19,'New York Knicks','New York',18,'Atlantico');
INSERT INTO franq VALUES(20,'Orlando Magic','Orlando',19,'Atlantico');
INSERT INTO franq VALUES(21,'Philadelphia 76ers','Philadelphia',20,'Atlantico');
INSERT INTO franq VALUES(22,'Phoenix Suns','Phoenix',21,'Medio-Oeste');
INSERT INTO franq VALUES(23,'Portland Trail Blazers','Portland',22,'Pacifico');
INSERT INTO franq VALUES(24,'Sacramento Kings','Sacramento',23,'Pacifico');
INSERT INTO franq VALUES(25,'San Antonio Spurs','San Antonio',24,'Medio-Oeste');
INSERT INTO franq VALUES(26,'Seattle Supersonics','Seattle',25,'Pacifico');
INSERT INTO franq VALUES(27,'Toronto Raptors','Toronto',26,'Central');
INSERT INTO franq VALUES(28,'Utah Jazz','Salt Lake City',27,'Medio-Oeste');
INSERT INTO franq VALUES(29,'Washington Wizards','Washington D.C.',28,'Atlantico');